apiVersion: kustomize.config.k8s.io/vibeta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: dispatcher-config
    files:
      - application.yml
    options:
      labels:
        app: dispatcher-service